spring.application.name=assignment

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=user
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
server.port=8087

# Enable the restart feature but exclude certain paths from triggering a restart
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**

# Enable the LiveReload feature
spring.devtools.livereload.enabled=true
