spring.application.name=assignment3
server.port=8081

# DataSource 1
#spring.datasource1.jdbc-url=jdbc:mysql://localhost:3306/employeeApp
#spring.datasource1.username=user
#spring.datasource1.password=password123
#spring.datasource1.driver-class-name=com.mysql.cj.jdbc.Driver

# DataSource 2
#spring.datasource2.jdbc-url=jdbc:mysql://localhost:3306/employeeApp1
#spring.datasource2.username=user
#spring.datasource2.password=password123
#spring.datasource2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=true
spring.jpa.show-sql=true
